export default [
  {
    id: 1,
    name: "Abdulsalam Muhammed-Jamiu",
    state: "Kogi state",
    age: 27,
    image: "/photo.png",
    email: "anatemuhammed@gmail.com",
    gender: "Male",
    del: "Delete",
  },
  {
    id: 2,
    name: "Aka'aba Musa",
    age: 27,
    state: "Kogi state",
    image: "/musa.jpg",
    email: "aka'abamusa@gmail.com",
    gender: "Male",
    del: "Delete",
  },
  {
    id: 3,
    name: "Momoh Jomoh Hashid",
    age: 27,
    state: "Kogi state",
    image: "/hashidu.png",
    email: "momohjomohhashidu@gmail.com",
    gender: "Male",
    del: "Delete",
  },
  {
    id: 4,
    name: "Usman de great",
    age: 27,
    state: "Kogi state",
    image: "/usman.png",
    email: "usmandegreat@gmail.com",
    gender: "Male",
    del: "Delete",
  },
  {
    id: 5,
    name: "Anate Abdulrahim",
    age: 30,
    state: "Kogi state",
    image: "/senbro.jpg",
    email: "anateabdulrahim@gmail.com",
    gender: "Male",
    del: "Delete",
  },
];
