export const mainproducts = [
  {
    img: "/menshoe/ms1.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms2.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms3.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms4.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms5.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms6.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms7.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms8.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms9.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms10.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms11.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms12.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms13.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms14.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms15.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms16.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms17.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms18.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms19.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms20.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/menshoe/ms1.jpg",
    name: "Shoe",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/wristwatch/w1.jpg",
    name: "watch",
    size: "21 ",
    price: "$60",
  },
  {
    img: "/wristwatch/w2.jpg",
    name: "watch",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/wristwatch/w3.jpg",
    name: "watch",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/wristwatch/w4.jpg",
    name: "watch",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/wristwatch/w5.jpg",
    name: "watch",
    size: "51 ",
    price: "$80",
  },
  {
    img: "/wristwatch/w6.jpg",
    name: "watch",
    size: "60 ",
    price: "$70",
  },
  {
    img: "/wristwatch/w7.jpg",
    name: "watch",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/wristwatch/w8.jpg",
    name: "watch",
    size: "25 ",
    price: "$30",
  },
  {
    img: "/wristwatch/w9.jpg",
    name: "watch",
    size: "31 ",
    price: "$20",
  },
  {
    img: "/wristwatch/w10.jpg",
    name: "watch",
    size: "11 ",
    price: "$10",
  },
  {
    img: "/projectbag/bag2.jpg",
    name: "Hand-Bag",
    size: "35 ",
    price: "$20",
  },
  {
    img: "/projectbag/bag3.jpg",
    name: "Hand-Bag",
    size: "35 ",
    price: "$30",
  },
  {
    img: "/projectbag/bag5.jpg",
    name: "Hand-Bag",
    size: "35 ",
    price: "$40",
  },
  {
    img: "/projectbag/bag6.jpg",
    name: "Hand-Bag",
    size: "30 ",
    price: "$40",
  },

  {
    img: "/projectbag/bag7.jpg",
    name: "Hand-Bag",
    size: "35",
    price: "$20",
  },
  {
    img: "/projectbag/bag8.jpg",
    name: "Hand-Bag",
    size: "75 ",
    price: "$60",
  },
  {
    img: "/projectbag/bag9.jpg",
    name: "Hand-Bag",
    size: "65",
    price: "$54",
  },

  {
    img: "/projectbag/bag10.jpg",
    name: "Hand-Bag",
    size: "45",
    price: "$70",
  },
  {
    img: "/projectbag/bag11.jpg",
    name: "Hand-Bag",
    size: "89",
    price: "$40",
  },
  {
    img: "/projectbag/bag18.jpg",
    name: " Hand-Bag",
    size: "35",
    price: "$20",
  },

  {
    img: "/projectbag/bag13.jpg",
    name: "Hand-Bag",
    size: "65",
    price: "$70",
  },
  {
    img: "/projectbag/bag14.jpg",
    name: "Hand-Bag",
    size: "70",
    price: "$60",
  },
  {
    img: "/projectbag/bag15.jpg",
    name: "Hand-Bag",
    size: "45",
    price: "$70",
  },

  {
    img: "/projectbag/bag16.jpg",
    name: "Hand-Bag",
    size: "25",
    price: "$30",
  },
  {
    img: "/projectbag/bag17.jpg",
    name: "Hand-Bag",
    size: "55",
    price: "$40",
  },
  {
    img: "/projectbag/bag18.jpg",
    name: "Hand-Bag",
    size: "55",
    price: "$70",
  },

  {
    img: "/projectbag/bag19.jpg",
    name: "Hand-Bag",
    size: "35",
    price: "$20",
  },
  {
    img: "/projectbag/bag13.jpg",
    name: "Hand-Bag",
    size: "45",
    price: "$50",
  },
  {
    img: "/projectbag/bag20.jpg",
    name: "Hand-Bag",
    size: "25",
    price: "$60",
  },

  {
    img: "/projectbag/bag10.jpg",
    name: "Hand-Bag",
    size: "70",
    price: "$80",
  },
  {
    img: "/projectbag/bag17.jpg",
    name: "Hand-Bag",
    size: "85",
    price: "$50",
  },
  {
    img: "/projectbag/bag11.jpg",
    name: "Hand-Bag",
    size: "32",
    price: "$10",
  },

  {
    img: "/projectbag/bag6.jpg",
    name: "Hand-Bag",
    size: "35",
    price: "$40",
  },
  {
    img: "/projectbag/bag5.jpg",
    name: "Hand-Bag",
    size: "40",
    price: "$30",
  },
  {
    img: "/projectcap/cap2.jpg",
    name: "Cap",
    size: "35 ",
    price: "$30",
  },
  {
    img: "/projectcap/cap3.jpg",
    name: "Cap",
    size: "35 ",
    price: "$20",
  },
  {
    img: "/projectcap/cap4.jpg",
    name: "Cap",
    size: "35 ",
    price: "$30",
  },
  {
    img: "/projectcap/cap5.jpg",
    name: "Cap",
    size: "35 ",
    price: "$40",
  },
  {
    img: "/projectcap/cap6.jpg",
    name: "Cap",
    size: "30 ",
    price: "$40",
  },

  {
    img: "/projectcap/cap7.jpg",
    name: "Cap",
    size: "35",
    price: "$20",
  },
  {
    img: "/projectcap/cap8.jpg",
    name: "Cap",
    size: "75 ",
    price: "$60",
  },
  {
    img: "/projectcap/cap9.jpg",
    name: "Cap",
    size: "65",
    price: "$54",
  },

  {
    img: "/projectcap/cap10.jpg",
    name: "Cap",
    size: "45",
    price: "$70",
  },
  {
    img: "/projectcap/cap11.jpg",
    name: "Cap",
    size: "89",
    price: "$40",
  },
  {
    img: "/projectcap/cap12.jpg",
    name: " Cap",
    size: "35",
    price: "$20",
  },

  {
    img: "/projectcap/cap13.jpg",
    name: "Cap",
    size: "65",
    price: "$70",
  },
  {
    img: "/projectcap/cap14.jpg",
    name: "Cap",
    size: "70",
    price: "$60",
  },
  {
    img: "/projectcap/cap15.jpg",
    name: "Cap",
    size: "45",
    price: "$70",
  },

  {
    img: "/projectcap/cap16.jpg",
    name: "Cap",
    size: "25",
    price: "$30",
  },
  {
    img: "/projectcap/cap18.jpg",
    name: "Cap",
    size: "55",
    price: "$40",
  },
  {
    img: "/projectcap/cap17.jpg",
    name: "Cap",
    size: "55",
    price: "$70",
  },

  {
    img: "/projectcap/cap19.jpg",
    name: "Cap",
    size: "35",
    price: "$20",
  },
  {
    img: "/projectcap/cap7.jpg",
    name: "Cap",
    size: "45",
    price: "$50",
  },
  {
    img: "/projectcap/cap9.jpg",
    name: "Cap",
    size: "25",
    price: "$60",
  },

  {
    img: "/projectcap/cap18.jpg",
    name: "Cap",
    size: "70",
    price: "$80",
  },
  {
    img: "/projectcap/cap2.jpg",
    name: "Cap",
    size: "85",
    price: "$50",
  },
  {
    img: "/projectcap/cap4.jpg",
    name: "Cap",
    size: "32",
    price: "$10",
  },

  {
    img: "/projectcap/cap5.jpg",
    name: "Cap",
    size: "35",
    price: "$40",
  },
  {
    img: "/projectcap/cap20.jpg",
    name: "Cap",
    size: "40",
    price: "$30",
  },
];
