export const profiles = [
  {
    name: "Musa",
    img: "/Routerphoto/Musa.jpg",
    gender: "Male",
    age: 27,
    state: " Kogi state",
    email: "musaakidi@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Anate",
    img: "/Routerphoto/photome.png",
    gender: "Male",
    age: 27,
    state: " Adamawa state",
    email: "anatemuhammed@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Hashidu",
    img: "/Routerphoto/hashidu.png",
    gender: "Male",
    age: 27,
    state: " Enugu state",
    email: "hashibibah@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Abdulhamid",
    img: "/Routerphoto/hamid.jpg",
    gender: "Male",
    age: 27,
    state: " zamfara state",
    email: "sirhamid@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Abdulrahim",
    img: "/Routerphoto/senbro.jpg",
    gender: "Male",
    age: 27,
    state: " sokoto state",
    email: "senbro@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Abbas",
    img: "/Routerphoto/myAbbass.jpg",
    gender: "Male",
    age: 27,
    state: " zaria state",
    email: "abbas@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Huzy",
    img: "/Routerphoto/Huzy50.jpg",
    gender: "Male",
    age: 27,
    state: " Gombe state",
    email: "huzy50@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Hassan",
    img: "/Routerphoto/hassan001.jpg",
    gender: "Male",
    age: 27,
    state: " Kaduna state",
    email: "hassan@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Usman",
    img: "/Routerphoto/usman.png",
    gender: "Male",
    age: 27,
    state: " Kwara state",
    email: "usmasndegreat@gmail.com",

    tel: "07036238110",
  },
  {
    name: "My-Love",
    img: "/Routerphoto/mylove.png",
    gender: "Female",
    age: 10,
    state: " kogi state",
    email: "mylove@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Mr web",
    img: "/Routerphoto/web1.jpg",
    gender: "Male",
    age: 27,
    state: " yola state",
    email: "mrweb@gmail.com",
    tel: "07036238110",
  },
  {
    name: "Sir web ",
    img: "/Routerphoto/web2.jpg",
    gender: "Male",
    age: 27,
    state: " Ekiti State",
    email: "sirweb@gmail.com",
    tel: "07013862792",
  },
  {
    name: " Men ",
    img: "/Routerphoto/friend.png",
    gender: "Male",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "Star web ",
    img: "/Routerphoto/web7.png",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: " web dev ",
    img: "/Routerphoto/web10.jpg",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "full-stack ",
    img: "/Routerphoto/web8.jpg",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "parksing ",
    img: "/Routerphoto/web3.png",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "frolasha ",
    img: "/Routerphoto/web6.jpg",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "franking ",
    img: "/Routerphoto/web2.jpg",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "fanshan ",
    img: "/Routerphoto/web1.jpg",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "profancy ",
    img: "/Routerphoto/dev.png",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "developer ",
    img: "/Routerphoto/web9.jpg",
    gender: "Male",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "Sterling ",
    img: "/Routerphoto/dev.png",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
  {
    name: "developer ",
    img: "/Routerphoto/coding.jpg",
    gender: "Female",
    age: 27,
    state: " Edo State",
    email: "senior@gmail.com",
    tel: "07017630492",
  },
];
